[package]
name = "crack_md5"
version = "1.0.0"
authors = ["Transmissions <greenfeatherhelp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
num-format = "0.4.0"

[profile.dev]
opt-level = 3
